name: checkthat-subjectivity
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - sentence-transformers
  - scikit-learn
  - pip
  - pip:
      - matplotlib
      - huggingface-hub
      - networkx
      - tf-keras
      - numpy
      - pandas
      - pillow
      - pytz
      - requests
      - seaborn
      - safetensors
      - scipy
      - tokenizers
      - torch
      - tqdm
      - transformers
      - tensorflow
      - git+https://github.com/huggingface/transformers
      - tiktoken
      - ipykernel
      - tqdm
      - unidecode
      - pyspark>=3.4.0
      - pyarrow
      # developer tools
      - jupyterlab
      - ruff
      - pre-commit
      - pytest