name: checkthat-subjectivity
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - rerankers
  - matplotlib
  - scikit-learn
  - networkx
  - numpy
  - pandas
  - polars
  - pillow
  - pytz
  - requests
  - safetensors
  - scikit-learn
  - scipy
  - sentence-transformers
  - seaborn
  - tokenizers
  - tqdm
  - tiktoken
  - ruff
  - pip
  - pacmap
  - umap-learn
  - pip:
    - transformers
    - torch
    - huggingface-hub
