data:
  dir: "/storage/coda1/p-dsgt_clef2025/0/shared/checkthat-2025-subjectiv-data"
  train: "raw_data/english/train_en.tsv"
  train_pred: "raw_data/english/train_generated_en.tsv"

llm:
  provider: openai
  class_name: ChatOpenAI
  model_config: {
    model_name: gpt-4o-mini,
    temperature: 0.0,
    max_tokens: 100,
    top_p: 0.9,
    frequency_penalty: 0.0,
    presence_penalty: 0.0,
    max_retries: 3,
  }

  prompt: 
    system: "You are a helpful assistant who paraphrases sentences. You preserve the original sentence's subjectivity or objectivity."
  