data:
  dir: /Users/maximilianheil/OMSCS/07_CLEF/Task1/checkthat-2025-subject/data
  train_en: raw_data_2024/english/train_en.tsv 
  train_en_embedding: embeddings/english/train_en_embed
  fine_tuned_model_path: fine_tuned_models/english
  val_en: raw_data_2024/english/dev_en.tsv

train:
  train_test_split: 0.9
  batch_size: 120
  seed: 42
  epochs: 7
  learning_rate: 0.0001
  eps: 0.00000001
  early_stopping_patience: 3

encoder_model: 
  name: "MarieAngeA13/Sentiment-Analysis-BERT"
  add_special_tokens: true
  padding: "max_length"
  truncation: true
  return_attention_mask: true
  return_tensors: "pt"
  pad_to_max_length: true
  max_length: 128
  batch_size: 20
  hidden_dim: 768
  freeze_encoder: false  #try true/false (true: just finetuning classifier on top of encoder / false: finetuning classifier + encoder)
  dropout_ratio: 0.1
  mlp_dim: 256

dim_red_model:
  name: "umap"
  n_neighbors: 15
  n_components: 2
  metric: euclidean
  random_state: 42

visualization:
  fig_dir: "/storage/coda1/p-dsgt_clef2025/0/shared/checkthat-2025-subjectiv-data/fig"
  data_type: "png"
  figure_size: [6, 6]